### ISSUE TITLE
License of tex file.

### ISSUE THREAD

**Issue by jnew** [nyqvist/ClearCase_Cheat_Sheet#2]
Hello,

I understand this is an old project, but I am wondering if it is okay to include the source for this document within my own tex files. There is no license file in the repo, and I like to ask people before just cloning/forking and including code. Thanks for your time.

**Comment by nyqvist** [comment]
Hi!

Sorry for the late reply, I did not see you message until now... I added a license file to the project. Feel free to use my code.

Thanks
